FROM linkerlab/rpi-omxplayer 
MAINTAINER pishon <kuczynskilukasz@gmail.com>

apt-get update
apt-get install curl

curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

sudo apt install -y nodejs

apt-get install git

git clone https://github.com/pishon/radiogaga.git
cd radiogaga
npm install



